name:                ParticleTracking
version:             0.1.0.0
github:              "githubuser/ParticleTracking"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ParticleTracking#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq
- directory
- filepath
- gnuplot
- hashable
- hmatrix
- hmatrix-gsl
- JuicyPixels
- monad-parallel
- parallel
- repa
- time
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  ParticleTracking-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    - -j8
    - -main-is Main
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -fllvm
    - -optlo-O3
    dependencies:
    - ParticleTracking

tests:
  FindParticles-test:
    main:                FindParticles.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    - -j8
    - -main-is FindParticles
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -fllvm
    - -optlo-O3
    dependencies:
    - ParticleTracking
    
  ParticleBrightness-test:
    main:                ParticleBrightness.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    - -j8
    - -main-is ParticleBrightness
    - -fno-liberate-case
    - -funfolding-use-threshold1000
    - -fllvm
    - -optlo-O3
    dependencies:
    - ParticleTracking
